### PR TITLE
Fabrid/data plane

### PR DESCRIPTION
**Pull request by marcodermatt**
This change is [Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/4)

### CODE REVIEW

**Review by jeltevanbommel — COMMENTED** [review]
> Reviewed 94 of 94 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/4)* status: all files reviewed, 14 unresolved discussions (waiting on @marcodermatt)

___
*[`control/cmd/control/main.go` line 352 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XWn5_EOfQ6gmTUBQY:-O3XWn5_EOfQ6gmTUBQZ:b-lkuv2a) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/control/cmd/control/main.go#L352)):*
> ```Go
> 	// Handle fabrid map and policy requests
> 	if globalCfg.Fabrid.Enabled {
> 		polFetcher := fabridgrpc.BasicFabridControlPlaneFetcher{
> ```

Feels a bit weird to PR these name changes to the control plane, but I guess that is what we get when we split up the PR.
___
*[`daemon/internal/servers/grpc.go` line 197 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XYCiY1BkAmZWVRlpA:-O3XYCiY1BkAmZWVRlpB:bxfiwd1) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/daemon/internal/servers/grpc.go#L197)):*
> ```Go
> // to be used directly in the combinator.
> func fetchMaps(ctx context.Context, ia addr.IA, client experimental.FABRIDIntraServiceClient,
> 	digest []byte) combinator.FabridMapEntry {
> ```

Import from combinator could go in a separate package, put it in pkg/experimental/fabrid/defs.go?
___
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 136 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XdRzW9r8x9PIems0h:-O3XdRzW9r8x9PIems0i:b3s3m5v) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L136)):*
> ```Go
> }
> 
> func EncryptPolicyID(f fabrid.PolicyID, id *ext.IdentifierOption,
> ```

nit: bit of duplicate code here, could be combined with `ComputePolicyID` and just return `buf[0]` such that the caller can xor it with the encrypted policy id
___
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 208 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xe7oi3G4lL7VRkD6X:-O3Xe7oi3G4lL7VRkD6Y:bvg4ztk) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L208)):*
> ```Go
> 				}
> 				key = asHostKey.Key
> 			}
> ```

for readability



_Suggestion:_
```Go
			var key drkey.Key
			var found bool
			if meta.ASLevelKey {
				key, found = asAsKeys[hops[i].IA]
			} else {
				key, found = asHostKeys[hops[i].IA]
			}
			if !found {
				return serrors.New("InitValidators expected AS to AS key but was not in"+
					" dictionary", "AS", hops[i].IA)
			}
```
___
*[`pkg/experimental/fabrid/crypto/fabrid_crypto_test.go` line 233 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xhfwj7pR0XF5VT9wO:-O3Xhfwj7pR0XF5VT9wP:undefined) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/pkg/experimental/fabrid/crypto/fabrid_crypto_test.go#L233)):*
> ```Go
> 					hops := make([]snet.HopInterface, len(f.HopfieldMetadata))
> 					//ingresses := []uint16{}
> 					//egresses := []uint16{}
> ```


___
*[`pkg/snet/path.go` line 183 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XasgV5DkRfGuhHTrn:-O3XasgV5DkRfGuhHTro:b-x9uat5) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/5e46d4b96812c6a65571981c00ef49dc86c2f044/pkg/snet/path.go#L183)):*
> ```Go
> 		InternalHops:    append(pm.InternalHops[:0:0], pm.InternalHops...),
> 		Notes:           append(pm.Notes[:0:0], pm.Notes...),
> 		FabridEnabled:   append(pm.FabridEnabled[:0:0], pm.FabridEnabled...),
> ```

Again a bit weird to PR FabridEnabled first and then remove it again. This file should not have any changes in control plane PR right?
___
*[`private/path/combinator/fabrid_accumulator.go` line 1 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xm3ZMDwdfsCqn87I8:-O3Xm3ZMDwdfsCqn87I9:b45h) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/private/path/combinator/fabrid_accumulator.go#L1)):*
> ```Go
> // Copyright 2018 ETH Zurich, Anapaya Systems
> ```





_Suggestion:_
```Go
// Copyright 2024 ETH Zurich
```
___
*[`private/path/fabridquery/matchlist.go` line 63 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xm__o9wQ_-S0BLN0N:-O3Xm__o9wQ_-S0BLN0O:bkkdxl5) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/private/path/fabridquery/matchlist.go#L63)):*
> ```Go
> 		if selected == nil {
> 			pols[i] = nil
> 			fmt.Println(i, " is not using a policy")
> ```

Minor do we want to keep this? It's good for the sake of debugging.
___
*[`private/path/fabridquery/matchlist_test.go` line 83 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xmwyw7D6Y2odnsRgx:-O3Xmwyw7D6Y2odnsRgy:b-fang1c) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/private/path/fabridquery/matchlist_test.go#L83)):*
> ```Go
> func TestPolicies(t *testing.T) {
> 
> }
> ```

The `.Policies()` function is already tested for the the results of the other tests. 
___
*[`router/config/config.go` line 101 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XoXzA9Sjqez-Zzz8j:-O3XoXzB1chQxVOFrcGJ:undefined) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/router/config/config.go#L101)):*
> ```Go
> 			return serrors.New("Provided router config is invalid." +
> 				"Enabling FABRID requires adding it to the DRKey protocols.")
> 		}
> ```





_Suggestion:_
```Go
	if cfg.Fabrid {
		if !slices.Contains(cfg.DRKey, "FABRID") {
			return serrors.New("Provided router config is invalid." +
				"Enabling FABRID requires adding it to the DRKey protocols.")
		}
```
___
*[`router/control/drkey.go` line 59 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XinSS7uCafd1v7d_-:-O3XinSTEEjSBc2ByvC5:bsdfu1c) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/router/control/drkey.go#L59)):*
> ```Go
> 
> func (d *DRKeyProvider) AddSecret(protocolID int32, sv SecretValue) error {
> 	if d == nil {
> ```

`if d.drKeySecrests == nil {` is enough right?
`d == nil` happening would be quite exotic?
___
*[`router/control/drkey.go` line 81 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xj6qA1ipR3_Yh7SiT:-O3Xj6qA1ipR3_Yh7SiU:bhhnbsx) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/router/control/drkey.go#L81)):*
> ```Go
> 
> func (d *DRKeyProvider) getSecret(protocolID int32, t time.Time) (*SecretValue, error) {
> 	secrets := d.drKeySecrets[protocolID]
> ```

here too check if d.drKeySecrets == nil
___
*[`router/control/fetcher.go` line 103 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XjVK068Ho6os-n_xF:-O3XjVK068Ho6os-n_xG:b-7h4u3n) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/router/control/fetcher.go#L103)):*
> ```Go
> 		for _, ipRange := range ipArray.Entry {
> 			var m net.IPMask
> 			if len(ipRange.Ip) == 4 { //TODO(jvanbommel): test this
> ```

works
___
*[`scion/cmd/scion/ping.go` line 204 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xk22O1Xz2Oj_LfZyv:-O3Xk22O1Xz2Oj_LfZyw:b-y45eyz) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/scion/cmd/scion/ping.go#L204)):*
> ```Go
> 				return err
> 			}
> 			fmt.Println(cs.Path(pingPath))
> ```

Only for debugging? Although the colors are nice.

**Review by rohrerj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/4)* status: 89 of 94 files reviewed, 14 unresolved discussions (waiting on @jeltevanbommel and @marcodermatt)

___
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 208 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xe7oi3G4lL7VRkD6X:-O3bFSuN18N6VTR7c_6P:br2z94e) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L208)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

for readability
</blockquote></details>

Modified
___
*[`pkg/experimental/fabrid/crypto/fabrid_crypto_test.go` line 233 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xhfwj7pR0XF5VT9wO:-O3bDitF6QJ7bUpFfsCI:ba3dfob) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/pkg/experimental/fabrid/crypto/fabrid_crypto_test.go#L233)):*
> ```Go
> 					hops := make([]snet.HopInterface, len(f.HopfieldMetadata))
> 					//ingresses := []uint16{}
> 					//egresses := []uint16{}
> ```

Removed
___
*[`router/config/config.go` line 101 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XoXzA9Sjqez-Zzz8j:-O3bDUmD-r0RPE2yQFUF:b-bw8e14) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/router/config/config.go#L101)):*
> ```Go
> 			return serrors.New("Provided router config is invalid." +
> 				"Enabling FABRID requires adding it to the DRKey protocols.")
> 		}
> ```

Updated.
___
*[`router/control/drkey.go` line 59 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XinSS7uCafd1v7d_-:-O3bCLHv9hE-FsLmNuF-:b28mhj4) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/router/control/drkey.go#L59)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

`if d.drKeySecrests == nil {` is enough right?
`d == nil` happening would be quite exotic?
</blockquote></details>

Right. If the router is started the way it should be, ```d == nil``` should never happen. I removed it
___
*[`router/control/drkey.go` line 81 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xj6qA1ipR3_Yh7SiT:-O3bC_B8ChDlQQNXLoJM:b65c6un) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/router/control/drkey.go#L81)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

here too check if d.drKeySecrets == nil
</blockquote></details>

Added the error condition
___
*[`router/control/fetcher.go` line 103 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XjVK068Ho6os-n_xF:-O3bClao1GpCVbWIu0W_:bpg42v9) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/router/control/fetcher.go#L103)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

works
</blockquote></details>

Good. I removed the comment

**Review by marcodermatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/4)* status: 89 of 94 files reviewed, 14 unresolved discussions (waiting on @jeltevanbommel)

___
*[`pkg/snet/path.go` line 183 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XasgV5DkRfGuhHTrn:-O3bc_NK4N0zjcjz7l5a:b-tskikt) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/5e46d4b96812c6a65571981c00ef49dc86c2f044/pkg/snet/path.go#L183)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

Again a bit weird to PR FabridEnabled first and then remove it again. This file should not have any changes in control plane PR right?
</blockquote></details>

Yeah not great, but that's the path returned by SD, so it needs to be in the control plane PR to compile. I think we can leave it, otherwise we would either have to move the FabridInfo stuff to control plane, or SD to data plane.
___
*[`private/path/fabridquery/matchlist.go` line 63 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xm__o9wQ_-S0BLN0N:-O3beeJ71c9tacl30Uao:b-cab0jc) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/private/path/fabridquery/matchlist.go#L63)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

Minor do we want to keep this? It's good for the sake of debugging.
</blockquote></details>

I think we can leave it for now. There's no real good place to print the information instead, as the path object itself does not know which policies are selected.
___
*[`scion/cmd/scion/ping.go` line 204 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xk22O1Xz2Oj_LfZyv:-O3bgaRD1TuNjmpOozLk:bwi7o6v) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/scion/cmd/scion/ping.go#L204)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

Only for debugging? Although the colors are nice.
</blockquote></details>

printf("Using path:\\n  %s\\n\\n", pingPath)
is a few lines down, but it doesn't print the policies. We could replace that maybe

[17-ffaa:1:1159 ~ZERO~ 1>480 17-ffaa:0:1107 ~~ 1>4 17-ffaa:0:1102 ~~]
Using path:
  Hops: [17-ffaa:1:1159 1>480 17-ffaa:0:1107 1>4 17-ffaa:0:1102] MTU: 1472 NextHop: 127.0.0.1:30001

**Comment by jeltevanbommel** [comment]
*[`control/cmd/control/main.go` line 352 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XWn5_EOfQ6gmTUBQY:-O3bqCUo3C1Zr9lFuez-:bug6cx7) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/control/cmd/control/main.go#L352)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

Feels a bit weird to PR these name changes to the control plane, but I guess that is what we get when we split up the PR.
</blockquote></details>

it's good after discussion

**Comment by jeltevanbommel** [comment]
*[`daemon/internal/servers/grpc.go` line 197 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XYCiY1BkAmZWVRlpA:-O3bqTBNAxW87R7kBkAR:b-yocbhc) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/daemon/internal/servers/grpc.go#L197)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

Import from combinator could go in a separate package, put it in pkg/experimental/fabrid/defs.go?
</blockquote></details>

@marcodermatt

**Comment by jeltevanbommel** [comment]
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 136 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XdRzW9r8x9PIems0h:-O3brXzm8N2Hlt-zmbMK:bbb3jlz) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L136)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

nit: bit of duplicate code here, could be combined with `ComputePolicyID` and just return `buf[0]` such that the caller can xor it with the encrypted policy id
</blockquote></details>

`calculatePolicyEncryptionKey`
Called by `DecryptPolicyID` and `EncryptPolicyID`
@jeltevanbommel

**Comment by jeltevanbommel** [comment]
*[`private/path/combinator/fabrid_accumulator.go` line 1 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xm3ZMDwdfsCqn87I8:-O3bsjuiBvhc1tekw_Qp:b-149ora) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/private/path/combinator/fabrid_accumulator.go#L1)):*
> ```Go
> // Copyright 2018 ETH Zurich, Anapaya Systems
> ```

@marcodermatt

**Comment by jeltevanbommel** [comment]
*[`private/path/fabridquery/matchlist.go` line 63 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xm__o9wQ_-S0BLN0N:-O3bu0qR5w4EomCOpzfO:b-o1wwds) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/private/path/fabridquery/matchlist.go#L63)):*
<details><summary><i>Previously, marcodermatt wrote…</i></summary><blockquote>

I think we can leave it for now. There's no real good place to print the information instead, as the path object itself does not know which policies are selected.
</blockquote></details>

@jeltevanbommel

**Review by jeltevanbommel — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/4)* status: all files reviewed, 6 unresolved discussions (waiting on @marcodermatt)

**Review by jeltevanbommel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/4)* status: 92 of 94 files reviewed, 4 unresolved discussions (waiting on @marcodermatt)

___
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 136 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3XdRzW9r8x9PIems0h:-O3c4h9KADk8UlRLaoRC:bb6un1j) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L136)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

`calculatePolicyEncryptionKey`
Called by `DecryptPolicyID` and `EncryptPolicyID`
@jeltevanbommel
</blockquote></details>

Done
___
*[`private/path/fabridquery/matchlist_test.go` line 83 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xmwyw7D6Y2odnsRgx:-O3c4jSIDNq6XouTxGUP:bb6un1j) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/private/path/fabridquery/matchlist_test.go#L83)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

The `.Policies()` function is already tested for the the results of the other tests.
</blockquote></details>

Done

**Review by jeltevanbommel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/4)* status: 92 of 94 files reviewed, 2 unresolved discussions (waiting on @marcodermatt)

___
*[`private/path/fabridquery/matchlist.go` line 63 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xm__o9wQ_-S0BLN0N:-O3cE14P5wZPlZ_-5VeS:b-fthqqp) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/private/path/fabridquery/matchlist.go#L63)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

@jeltevanbommel
</blockquote></details>

Done see https://github.com/jeltevanbommel/scionlab/commit/21ceae2902a941eafe7a1419bdeeac841865d501
___
*[`scion/cmd/scion/ping.go` line 204 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xk22O1Xz2Oj_LfZyv:-O3cDwYD0feAIajpnOs8:b-fthqqp) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/scion/cmd/scion/ping.go#L204)):*
<details><summary><i>Previously, marcodermatt wrote…</i></summary><blockquote>

printf("Using path:\\n  %s\\n\\n", pingPath)
is a few lines down, but it doesn't print the policies. We could replace that maybe

[17-ffaa:1:1159 ~ZERO~ 1>480 17-ffaa:0:1107 ~~ 1>4 17-ffaa:0:1102 ~~]
Using path:
  Hops: [17-ffaa:1:1159 1>480 17-ffaa:0:1107 1>4 17-ffaa:0:1102] MTU: 1472 NextHop: 127.0.0.1:30001
</blockquote></details>

Done see https://github.com/jeltevanbommel/scionlab/commit/21ceae2902a941eafe7a1419bdeeac841865d501

**Review by marcodermatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/4)* status: 69 of 94 files reviewed, 2 unresolved discussions (waiting on @jeltevanbommel)

___
*[`private/path/combinator/fabrid_accumulator.go` line 1 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/4#-O3Xm3ZMDwdfsCqn87I8:-O3fgF-OE1H6ajcIHLUt:b-896fix) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/899387557ba2b21861b18622ef868ef1aab52340/private/path/combinator/fabrid_accumulator.go#L1)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

@marcodermatt
</blockquote></details>

Done.

**Pull request closed without merging**
